In [2]:
import numpy as np
arr = np.arange(0, 10)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr1 = arr.reshape(2,5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
A = np.array([[2,5], [7,6]])
B = np.array([[9,8], [10,4]])
print(A+B)

[[11 13]
 [17 10]]


In [5]:
print(A*B)

[[18 40]
 [70 24]]


In [6]:
C = np.dot(A,B)
print(np.dot(A,B))

[[ 68  36]
 [123  80]]


In [7]:
print(np.transpose(A))

[[2 7]
 [5 6]]


In [8]:
D = np.dot(A,B)
print(np.dot((np.transpose(A)),B))

[[ 88  44]
 [105  64]]


In [9]:
Elements = arr[arr<7]
print(Elements)

[0 1 2 3 4 5 6]


In [10]:
arr2 = np.array([2, -4, 8, -6, 1, 5, -100])
arr2[arr2<0] = 0
print(arr2)

[2 0 8 0 1 5 0]


In [11]:
print(np.flip(arr2))

[0 5 1 0 8 0 2]


In [12]:
arr3 = np.array([2, 34, 5, 67, 12, 3, 16])
print(np.mean(arr3))

19.857142857142858


In [13]:
print(np.median(arr3))

12.0


In [14]:
print(np.std(arr3))

21.78747065519585


In [15]:
np.save("new array.npy", arr3)

In [16]:
print(np.load("new array.npy"))

[ 2 34  5 67 12  3 16]


In [17]:
arr4 = np.array([[2,24], [68,45]])
np.savetxt("arr.csv", arr4)

In [18]:
print(np.loadtxt("arr.csv"))

[[ 2. 24.]
 [68. 45.]]


In [19]:
print(np.hstack((A,B)))

[[ 2  5  9  8]
 [ 7  6 10  4]]


In [20]:
import pandas as pd

In [21]:
df = pd.read_csv(r"C:\Users\ASUS\Downloads\Jennifer A - AirPassengers.csv - Jennifer A - AirPassengers.csv.csv")

In [22]:
print(df.head())

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121


In [25]:
Passengers = df['#Passengers'].to_numpy()

In [26]:
Total_passengers = np.sum(Passengers)
print(Total_passengers)

40363


In [28]:
Average = np.mean(Passengers)
print(np.mean(Passengers))

280.2986111111111


In [38]:
First_year = np.sqrt(Passengers[0:12])
print(First_year)

[10.58300524 10.86278049 11.48912529 11.35781669 11.         11.61895004
 12.16552506 12.16552506 11.66190379 10.90871211 10.19803903 10.86278049]


In [45]:
df['Year'] = pd.to_datetime(df['Month']).dt.year

In [46]:
df

Month  #Passengers  Year
0    1949-01          112  1949
1    1949-02          118  1949
2    1949-03          132  1949
3    1949-04          129  1949
4    1949-05          121  1949
..       ...          ...   ...
139  1960-08          606  1960
140  1960-09          508  1960
141  1960-10          461  1960
142  1960-11          390  1960
143  1960-12          432  1960

[144 rows x 3 columns]

In [47]:
Passengers_year = df.groupby('Year')['#Passengers'].sum()

In [48]:
print(Passengers_year)

Year
1949    1520
1950    1676
1951    2042
1952    2364
1953    2700
1954    2867
1955    3408
1956    3939
1957    4421
1958    4572
1959    5140
1960    5714
Name: #Passengers, dtype: int64


In [61]:
passengers_1950 = Passengers[12:24]

In [62]:
print(passengers_1950)

[115 126 141 135 125 149 170 170 158 133 114 140]


In [63]:
passengers_1951 = Passengers[24:36]

In [65]:
print(passengers_1951)

[145 150 178 163 172 178 199 199 184 162 146 166]


In [66]:
Total_1950 = sum(passengers_1950)

In [67]:
print(Total_1950)

1676


In [68]:
Total_1951 = sum(passengers_1951)
print(Total_1951)

2042


In [74]:
A = np.mean(passengers_1950)
print(np.mean(passengers_1950))

139.66666666666666


In [75]:
B = np.mean(passengers_1951)
print(np.mean(passengers_1951))

170.16666666666666


In [78]:
np.subtract(B,A)

30.5

In [89]:
print('modify_1951', np.copy(passengers_1951)*3.0)

modify_1951 [435. 450. 534. 489. 516. 534. 597. 597. 552. 486. 438. 498.]


In [90]:
 print(passengers_1951)

[145 150 178 163 172 178 199 199 184 162 146 166]


In [95]:
np.random.seed(42)
forecast_1961 = np.random.uniform(100,600,12).astype(int)
actual_1960 = Passengers[-12:]

In [96]:
print(np.max(forecast_1961))

584


In [97]:
print(np.min(forecast_1961))

110


In [98]:
print(np.max(actual_1960))

622


In [100]:
print(np.min(actual_1960))

390


In [105]:
maximum = actual_1960[0]
for i in actual_1960:
    if i>maximum:
        maximum = i
print("max (1960)", maximum)

max (1960) 622


In [110]:
np.savetxt('forecast_1961.dat', forecast_1961)

In [116]:
np.loadtxt('forecast_1961.dat', skiprows=1)

array([575., 465., 399., 178., 177., 129., 533., 400., 454., 110., 584.])